#!/bin/bash

# Nautilus scripts varialbes
# NAUTILUS_SCRIPT_SELECTED_FILE_PATHS    newline-delimited paths for selected files (only if local)
# NAUTILUS_SCRIPT_SELECTED_URIS          newline-delimited URIs for selected files
# NAUTILUS_SCRIPT_CURRENT_URI            current location
# NAUTILUS_SCRIPT_WINDOW_GEOMETRY        position and size of current window

# cp -r src/* ~/.local/share/nautilus/scripts/
# ln -s src/Convert... ~/.local/share/nautilus/scripts/Convert...
nautDir="$HOME/.local/share/nautilus/scripts/"
srcDir="$(pwd)/src/"
scriptList=("Convert" "Metadata" "ytdl")
for f in ${scriptList[@]}; do
    ln -s "$srcDir/$f" "$nautDir/$fn"
done
