#!/bin/bash
# 2023 diasgc

source .common

fname=$(zenity zenity --width=400 --title="Create" --entry --text="Enter filename")
test -n "${fname}" && test "${fname}" = *"/"* || touch "${fileListDir}/${fname}"
