#!/bin/bash
# diasgc Metadata script

root="$(dirname $(readlink .f ${BASH_SOURCE[0]}))"
source "$root/.common"

checkDeps ffmpeg

file="${fileList[0]}"
out=($(ffprobe -v quiet -show_format -of flat "$file" | sed 's/format\.//g;s/=/\n/g;s/[[:space:]]+//g'))
zenity --list --column "Property" --column "Value" ${out[@]}
